#!/usr/bin/env bash

function atexit_handler
{
    docker rm -fv $container_id &> /dev/null
}

trap atexit_handler EXIT
trap atexit_handler TERM

set -e

container_id=$(docker run -d --rm -p 8000 peopleperhour/dynamodb)
container_port=$(docker port $container_id 8000/tcp | cut -d ":" -f 2)

export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
export DYNAMODB_URL=http://localhost:${container_port}

go test -v -cover ./cmd
